//! Distinct Component containers.
//!
//! In this engine, Components are divided up into [`Level`]s. Each `Level`
//! contains a list of Components inside and a list of top-level Components.
//! Each `Level` renders and simulates physics independently.

use std::{
    any::{Any, TypeId},
    cell::{BorrowMutError, Cell, Ref, RefCell, RefMut},
    collections::{HashMap, hash_map::Entry},
};

use elsa::FrozenMap;
use thiserror::Error;

use crate::core::{
    GetError, GetMutError,
    component::{ComponentId, DynComponentId, IComponent, ISlotId},
    input::{InputEvent, SInputReceiverId},
    level::script::IScript,
    relations::{BuildTypeIdHasher, RELATIONS},
    rendering::RenderingQueue,
    util::gen_slot_vec::{RefCellGenSlotVec, SlotIndex},
    window::WindowId,
    world::World,
};

pub mod script;

trait IColumn: Any {
    fn len(&self) -> u32;

    fn remove(&self, index: SlotIndex);

    fn get_pairs(&self) -> Box<dyn Iterator<Item = SlotIndex> + '_>;

    fn get_dyn(&self, index: SlotIndex) -> Result<Ref<'_, dyn IComponent>, GetError>;
    fn get_dyn_mut(&self, index: SlotIndex) -> Result<RefMut<'_, dyn IComponent>, GetMutError>;
}

impl<C: IComponent> IColumn for RefCellGenSlotVec<C> {
    fn len(&self) -> u32 {
        self.len()
    }

    fn remove(&self, index: SlotIndex) {
        let _ = self.remove(index);
    }

    fn get_pairs(&self) -> Box<dyn Iterator<Item = SlotIndex> + '_> {
        Box::new(self.ids())
    }

    fn get_dyn(&self, index: SlotIndex) -> Result<Ref<'_, dyn IComponent>, GetError> {
        Ok(Ref::map(self.acquire(index)?, |c| -> &dyn IComponent { c }))
    }

    fn get_dyn_mut(&self, index: SlotIndex) -> Result<RefMut<'_, dyn IComponent>, GetMutError> {
        Ok(RefMut::map(
            self.acquire_mut(index)?,
            |c| -> &mut dyn IComponent { c },
        ))
    }
}

/// Container for an isolated set of Components, complete with its own physics simulation and
/// render targets.
///
/// Each `Level` is separate from every other. Components should only have children in the same
/// `Level` as themselves. Each `Level` has a list of root Components
pub struct Level {
    self_idx: Cell<Option<LevelId>>,
    component_columns: FrozenMap<TypeId, Box<dyn IColumn>, BuildTypeIdHasher>,
    top_level: RefCell<Vec<DynComponentId>>,

    scripts: RefCell<HashMap<TypeId, Box<dyn IScript>>>,

    rendering_queue: RefCell<RenderingQueue>,

    window: Cell<Option<WindowId>>,

    pub(crate) active: Cell<bool>,
}

#[derive(Error)]
/// Error produced by [`Level::add_script`].
pub enum AddScriptError<S> {
    #[error("borrow error: {0}")]
    /// Error trying to mutably borrow the Scripts
    Borrow(#[from] BorrowMutError),
    #[error("Script for type already exists")]
    /// Returned if a Script of the given type is already set on the [`Level`]
    AlreadyExists(S),
}

impl Level {
    pub(crate) fn new(self_idx: LevelId) -> Self {
        Self {
            self_idx: Cell::new(Some(self_idx)),
            component_columns: FrozenMap::default(),
            top_level: RefCell::new(Vec::new()),
            scripts: RefCell::new(HashMap::new()),
            rendering_queue: RefCell::new(RenderingQueue::new()),
            window: Cell::new(None),
            active: Cell::new(false),
        }
    }

    pub(crate) fn set_window(&self, window: WindowId) {
        self.window.set(Some(window));
    }

    pub(crate) fn unset_window(&self) {
        self.window.set(None);
    }

    pub(crate) fn get_rendering_queue(&self) -> Ref<'_, RenderingQueue> {
        self.rendering_queue.borrow()
    }

    /// Sets whether this `Level` is active or not.
    ///
    /// See [`Self::is_active`].
    ///
    /// `Level`s bound to a window are always active, regardless of what this is set to.
    pub fn set_active(&self, active: bool) -> bool {
        self.active.set(active);
        self.is_active()
    }

    /// Returns whether this `Level` is active or not.
    ///
    /// A `Level` starts as inactive, which means it is ignored for rendering
    /// and events like `idle`. Note that a `Level` bound to a window is always active.
    pub fn is_active(&self) -> bool {
        self.active.get() || self.window.get().is_some()
    }

    /// Returns the index of the bound window, if there is any.
    pub fn get_window(&self) -> Option<WindowId> {
        self.window.get()
    }

    /// Returns the [`LevelId`] that accesses this `Level`.
    pub fn id(&self) -> LevelId {
        self.self_idx.get().expect("level not active")
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Removes a component.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Attempts to mutably borrow the targeted Component's slot.
    pub fn remove_component_internal(&self, tyid: TypeId, slot: SlotIndex) {
        let Some(column) = self.component_columns.get(&tyid) else {
            return;
        };

        column.remove(slot);
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Inserts a component.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Mutably borrows the destination slot.
    pub fn insert_component_internal<C: IComponent>(&self, value: C) -> ComponentId<C> {
        let column = match self.component_columns.get(&TypeId::of::<C>()) {
            Some(o) => o,
            None => self
                .component_columns
                .insert(TypeId::of::<C>(), Box::new(RefCellGenSlotVec::<C>::new())),
        };

        if column.len() == u32::MAX {
            panic!("value inserted to full column");
        }

        let Some(column) = <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column) else {
            unreachable!()
        };

        let slot = column.insert(value);

        unsafe { ComponentId::from_parts(slot, self.id(), TypeId::of::<C>()) }
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Reserves a component.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Mutably borrows the reserved slot.
    pub fn reserve_slot_internal<C: IComponent>(&self) -> ComponentId<C> {
        let column = match self.component_columns.get(&TypeId::of::<C>()) {
            Some(o) => o,
            None => self
                .component_columns
                .insert(TypeId::of::<C>(), Box::new(RefCellGenSlotVec::<C>::new())),
        };

        if column.len() == u32::MAX {
            panic!("value inserted to full column");
        }

        let Some(column) = <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column) else {
            unreachable!()
        };

        let slot = column.reserve();

        unsafe { ComponentId::from_parts(slot, self.id(), TypeId::of::<C>()) }
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Fills a slot with a component.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Mutably borrows the targeted slot.
    pub fn fill_slot_internal<C: IComponent>(&self, slot: SlotIndex, value: C) {
        let Some(column) = self.component_columns.get(&TypeId::of::<C>()) else {
            return;
        };

        let Some(column) = <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column) else {
            return;
        };

        column.fill(slot, value);
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Acquires a component *immutably*.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Immutably borrows the Component's slot until the returned
    /// [`Ref`] is dropped.
    pub fn acquire_component_internal<C: IComponent>(
        &self,
        slot: SlotIndex,
    ) -> Result<Ref<'_, C>, GetError> {
        let column = self
            .component_columns
            .get(&TypeId::of::<C>())
            .ok_or(GetError::NotFound)?;

        let column =
            <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column).ok_or(GetError::NotFound)?;

        column.acquire(slot)
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Acquires a component *mutably*.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Mutably borrows the Component's slot until the returned
    /// [`RefMut`] is dropped.
    pub fn acquire_component_internal_mut<C: IComponent>(
        &self,
        slot: SlotIndex,
    ) -> Result<RefMut<'_, C>, GetMutError> {
        let column = self
            .component_columns
            .get(&TypeId::of::<C>())
            .ok_or(GetMutError::NotFound)?;

        let column =
            <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column).ok_or(GetMutError::NotFound)?;

        column.acquire_mut(slot)
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Acquires a component *dynamically*.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Immutably borrows the Component's slot until the returned
    /// [`Ref`] is dropped.
    pub fn acquire_component_internal_dyn(
        &self,
        tyid: TypeId,
        slot: SlotIndex,
    ) -> Result<Ref<'_, dyn IComponent>, GetError> {
        let column = self
            .component_columns
            .get(&tyid)
            .ok_or(GetError::NotFound)?;

        column.get_dyn(slot)
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Acquires a component *dynamically **and** mutably*.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    ///
    /// Mutably borrows the Component's slot until the returned
    /// [`RefMut`] is dropped.
    pub fn acquire_component_internal_dyn_mut(
        &self,
        tyid: TypeId,
        slot: SlotIndex,
    ) -> Result<RefMut<'_, dyn IComponent>, GetMutError> {
        let column = self
            .component_columns
            .get(&tyid)
            .ok_or(GetMutError::NotFound)?;

        column.get_dyn_mut(slot)
    }

    #[doc(hidden)]
    /// (**INTERNAL**) Removes all resources and Components, and marks the level as inactive.
    ///
    /// WARNING: This method is safe to use, but is intended to be used
    /// internally. It is only made public so it can be generated by a macro.
    /// Only use this if you know what you are doing.
    ///
    /// # Borrows
    /// Mutably borrows all Components and descendants.
    pub fn destroy_internal(&self, world: &World) {
        for top_id in self.top_level.borrow_mut().drain(..) {
            let (slot, top_tyid) = top_id.acquire_parts();
            let mut top = top_id.get_mut(world).expect("just acquired from top");
            top.destroy(world);
            drop(top);

            self.remove_component_internal(top_tyid, slot);
        }
    }

    /// Spawn a new Component at the end of the top level list.
    pub fn spawn_top_level<C: IComponent>(
        &self,
        world: &World,
        info: C::SpawnInfo,
    ) -> ComponentId<C> {
        let id = C::spawn(world, self.id().into(), info);
        self.top_level.borrow_mut().push(id.clone().into());
        id.get_mut(world)
            .expect("component was just added")
            .post_init(world);
        id
    }

    /// Returns an iterator over the IDs of all Components in the top level list.
    pub fn iter_top_level(&self) -> impl Iterator<Item = DynComponentId> + 'static {
        self.top_level.borrow().clone().into_iter()
    }

    /// Removes a Component from the top level list.
    ///
    /// # Borrows
    ///
    /// Mutably borrows the removed Component's slot, and the removed Component
    /// plus all of its descendants (via queue-based traversal) through
    /// [`destroy`](IComponent::destroy).
    pub fn remove_top_level(&self, world: &World, id: &DynComponentId) -> bool {
        let mut top_level = self.top_level.borrow_mut();

        let Some(position) = top_level.iter().position(|id2| id2 == id) else {
            return false;
        };

        top_level.remove(position);

        id.get_mut(world).expect("id is in world").destroy(world);
        let (slot, tyid) = id.acquire_parts();
        self.remove_component_internal(tyid, slot);

        true
    }

    /// Returns an iterator over all Components of a given type, as *immutable* borrows.
    ///
    /// # Borrows
    ///
    /// Immutably borrows each occupied slot of type `C` while iterating; each
    /// yielded [`Ref`] holds its borrow until dropped.
    pub fn iter_type<'a, C: IComponent>(&'a self) -> Box<dyn Iterator<Item = Ref<'a, C>> + 'a> {
        let Some(column) = self.component_columns.get(&TypeId::of::<C>()) else {
            return Box::new(std::iter::empty());
        };
        let column =
            <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column).expect("column is for type C");

        Box::new(column.iter())
    }

    /// Returns an iterator over all Components of a given type, as *mutable* borrows.
    ///
    /// # Borrows
    ///
    /// Mutably borrows each occupied slot of type `C` while iterating; each
    /// yielded [`RefMut`] holds its borrow until dropped.
    pub fn iter_type_mut<'a, C: IComponent>(
        &'a self,
    ) -> Box<dyn Iterator<Item = RefMut<'a, C>> + 'a> {
        let Some(column) = self.component_columns.get(&TypeId::of::<C>()) else {
            return Box::new(std::iter::empty());
        };
        let column =
            <dyn Any>::downcast_ref::<RefCellGenSlotVec<C>>(column).expect("column is for type C");

        Box::new(column.iter_mut())
    }

    /// Returns a list of all Components in the `Level` that can be identified by `D`.
    ///
    /// # Borrows
    ///
    /// Transiently immutably borrows each matching Component's slot during
    /// iteration.
    pub fn all_matching_ids<D: ISlotId>(&self) -> impl Iterator<Item = D> {
        let self_id = self.id();
        RELATIONS.iter_slot_types::<D>().flat_map(move |tyid| {
            // If the column exists, get all components in it.
            // If it doesn't, we need to match the type, so create a new Box
            match self.component_columns.get(&tyid) {
                Some(column) => column.get_pairs(),
                None => Box::new(std::iter::empty()),
            }
            .map(move |slot| unsafe { D::from_parts(slot, self_id, tyid) })
        })
    }

    /// Get the Script associated with the given ID.
    ///
    /// # Borrows
    ///
    /// Borrows **all** Scripts mutably.
    pub fn get_script<S: IScript>(&self) -> Result<Ref<'_, S>, GetError> {
        Ref::filter_map(self.scripts.try_borrow()?, |m| {
            Some(
                m.get(&TypeId::of::<S>())?
                    .downcast_ref()
                    .expect("typed ID should match stored type"),
            )
        })
        .map_err(|_| GetError::NotFound)
    }

    /// Get the Script associated with the given ID.
    ///
    /// # Borrows
    ///
    /// Borrows **all** Scripts mutably.
    pub fn get_script_mut<S: IScript>(&self) -> Result<RefMut<'_, S>, GetMutError> {
        RefMut::filter_map(self.scripts.try_borrow_mut()?, |m| {
            Some(
                m.get_mut(&TypeId::of::<S>())?
                    .downcast_mut()
                    .expect("typed ID should match stored type"),
            )
        })
        .map_err(|_| GetMutError::NotFound)
    }

    /// Remove a Script by static type.
    ///
    /// # Borrows
    ///
    /// Borrows **all** Scripts immutably.
    pub fn remove_script<S: IScript>(&self) -> Result<(), GetMutError> {
        if self
            .scripts
            .try_borrow_mut()?
            .remove(&TypeId::of::<S>())
            .is_some()
        {
            Ok(())
        } else {
            Err(GetMutError::NotFound)
        }
    }

    /// Adds a new script
    pub fn add_script<S: IScript>(
        &self,
        world: &World,
        script: S,
    ) -> Result<(), AddScriptError<S>> {
        let mut scripts = self.scripts.try_borrow_mut()?;
        match scripts.entry(TypeId::of::<S>()) {
            Entry::Occupied(_) => return Err(AddScriptError::AlreadyExists(script)),
            Entry::Vacant(v) => v.insert(Box::new(script)).post_init(world, self),
        }
        Ok(())
    }

    pub(crate) fn idle(&self, world: &World, delta: f32) {
        for script in self.scripts.borrow_mut().values_mut() {
            script.idle(world, self, delta);
        }

        for id in self.iter_top_level() {
            let mut comp = id.get_mut(world).expect("component was just acquired");
            comp.idle(world, delta);
        }
    }

    pub(crate) fn pre_phys(&self, world: &World, delta: f32) {
        for script in self.scripts.borrow_mut().values_mut() {
            script.pre_phys(world, self, delta);
        }

        for id in self.iter_top_level() {
            let mut comp = id.get_mut(world).expect("component was just acquired");
            comp.pre_phys(world, delta);
        }
    }

    pub(crate) fn post_phys(&self, world: &World, delta: f32) {
        for script in self.scripts.borrow_mut().values_mut() {
            script.post_phys(world, self, delta);
        }

        for id in self.iter_top_level() {
            let mut comp = id.get_mut(world).expect("component was just acquired");
            comp.post_phys(world, delta);
        }
    }

    pub(crate) fn raw_input(&self, world: &World, event: &InputEvent) {
        for script in self.scripts.borrow_mut().values_mut() {
            script.raw_input(world, self, event);
        }

        for comp in self.all_matching_ids::<SInputReceiverId>() {
            comp.get_mut(world)
                .expect("component was just acquired")
                .raw_input(world, event);
        }
    }
}

/// Non-owning index within the [`World`] of a [`Level`].
#[derive(Clone, Copy, Hash, PartialEq, Eq, Debug)]
pub struct LevelId(pub(crate) u32, pub(crate) u32);

/// Singly-owning index within the [`World`] of a [`Level`].
#[derive(Hash)]
pub struct LevelIdOwned(pub(crate) u32, pub(crate) u32);

impl LevelIdOwned {
    /// Returns a non-owning copy of this index.
    pub fn handle(&self) -> LevelId {
        LevelId(self.0, self.1)
    }

    /// Leaks the index. The [`Level`] will live until the [`World`] is dropped.
    ///
    /// Avoid silent-dropping a `LevelIdOwned`, as it logs an error unless
    /// you call this manually.
    pub fn leak(mut self) {
        self.0 = u32::MAX;
        self.1 = u32::MAX
    }
}

impl Drop for LevelIdOwned {
    fn drop(&mut self) {
        if self.0 != u32::MAX && self.1 != u32::MAX {
            tracing::warn!(
                handle.pos_idx = self.0,
                handle.gen_idx = self.1,
                "a LevelIdOwned was dropped without manually being leaked, preventing the Level \
                from being removed until the World is destroyed"
            );
        }
    }
}

impl PartialEq<LevelId> for LevelIdOwned {
    fn eq(&self, other: &LevelId) -> bool {
        &self.handle() == other
    }
}

impl PartialEq<LevelIdOwned> for LevelId {
    fn eq(&self, other: &LevelIdOwned) -> bool {
        self == &other.handle()
    }
}
